"""change event time columns

Revision ID: a1130d1cf82a
Revises: f76ab8f49753
Create Date: 2026-01-23 13:52:37.558471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1130d1cf82a'
down_revision: Union[str, Sequence[str], None] = 'f76ab8f49753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('last_run_on', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('next_run_on', sa.Date(), nullable=False))
    op.drop_column('events', 'next_run_at')
    op.drop_column('events', 'last_run_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('events', 'next_run_on')
    op.drop_column('events', 'last_run_on')
    # ### end Alembic commands ###
