"""add updated_at field on transactions

Revision ID: f76ab8f49753
Revises: 33dfbdeabc72
Create Date: 2025-11-30 19:10:47.829124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76ab8f49753'
down_revision: Union[str, Sequence[str], None] = '33dfbdeabc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###
