"""move storage to user

Revision ID: f7d9aa9ebf49
Revises: 1d63f7fa0610
Create Date: 2026-03-29 13:58:28.036925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d9aa9ebf49'
down_revision: Union[str, Sequence[str], None] = '1d63f7fa0610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storages')
    op.add_column('users', sa.Column('balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.create_table('storages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('storages_account_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('storages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('storages_pkey'))
    )
    # ### end Alembic commands ###
