"""relate transaction_types to accounts

Revision ID: 33dfbdeabc72
Revises: 48cc356fc4df
Create Date: 2025-11-12 17:55:08.776655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dfbdeabc72'
down_revision: Union[str, Sequence[str], None] = '48cc356fc4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('transaction_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'transaction_types', ['transaction_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'transaction_type_id')
    # ### end Alembic commands ###
